const axios = require('axios');
module.exports = async function (context, req) {
    context.log('Received incoming clubhouse webhook..');
    //let data = '{"name": "' + req.body.actions[0].name + '", "project_id": 50657, "description": "automagically generated by webhook", "owner_ids": ["' + req.body.actions[0].changes.owner_ids.adds[0] + '"], "story_links": [{"id":' + req.body.primary_id + ', "object_id":' + req.body.primary_id + ', "subject_id":' + req.body.primary_id + '}]}';
    let data = '{"name": "' + req.body.actions[0].name + '", "project_id": 50657, "description": "automagically generated by webhook", "owner_ids": ["' + req.body.actions[0].changes.owner_ids.adds[0] + '"]}';
    context.log(data);
    let axiosConfig = {
        headers: {
            'Content-Type': 'application/json;charset=utf-8'
        }
      };
    
    axios.post('https://api.clubhouse.io/api/beta/stories?token=YOUR-API-TOKEN', data, axiosConfig)
    .then(function (response) {
        console.log(response);
      })
      .catch(function (error) {
        console.log(error);
      });
}